version: "3.3"
services:
  web:
    build: .
    ports:
    - "3001:3001"
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081