version: "2.2"
services:
  web:
    build: .
    ports:
        - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo 
    ports:
      - "27017:27017"
    restart: always
    cpus: "0.5"
    mem_limit: 750m
    volumes:
            - data-docker 
